Downgrade promoted-builds version due to bugs in 3.3 and 3.4
related:

Promotion logs not accessible anymore after Jenkins upgrade
https://issues.jenkins-ci.org/browse/JENKINS-59600

NoSuchMethodError occurs when promoting a build using parametrized trigger
https://issues.jenkins-ci.org/browse/JENKINS-59704