Use plugin pipeline-model-definition for check instead of workflow-job
The workflow-job only would not work and fail with
java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/StepDescriptor

pipeline-model-definition is the plugin defined in the pom.xml so it makes better
sense to test against it.